// using System.Runtime.InteropServices;
//
// namespace Classic.Avalonia.Theme;
//
// public class NativeMethods
// {
//     private static int[] sysColors = new[]
//     {
//         13626101,
//         4325442,
//         3122647,
//         10789024,
//         10343916,
//         16777215,
//         0,
//         0,
//         0,
//         16777215,
//         10343916,
//         10343916,
//         13626101,
//         8388736,
//         16777215,
//         10343916,
//         3122647,
//         3122647,
//         0,
//         13626101,
//         13626101,
//         0,
//         10343916,
//         8388736,
//         16777215,
//         12632256,
//         3122647,
//         8965344,
//         9489616,
//         8388736,
//         10343916,
//         0,
//         0,
//         0,
//
//
//
//
//     };
//
//     private static int[] sysColors_luna = new[]
//     {
//         13160660,
//         9981440,
//         14898176,
//         14653050,
//         16777215,
//         16777215,
//         0,
//         0,
//         0,
//         16777215,
//         13160660,
//         13160660,
//         8421504,
//         12937777,
//         16777215,
//         14215660,
//         10070188,
//         10070188,
//         0,
//         16311512,
//         16777215,
//         6582129,
//         14872561,
//         0,
//         14811135,
//         11908533,
//         8388608,
//         16749885,
//         15448477,
//         12937777,
//         14215660,
//         0,
//         0,
//     };
//
//     //[DllImport("user32.dll", CharSet = System.Runtime.InteropServices.CharSet.Auto)]
//     public static int GetSysColor(int nIndex)
//     {
//         if (nIndex < 0 || nIndex >= sysColors.Length)
//             return 0;
//         return sysColors[nIndex];
//         //return System.Drawing.SystemColors.
//     }
//
//     //[DllImport("user32.dll")]
//     internal static int GetSystemMetrics(SM nIndex)
//     {
//         return nIndex switch
//         {
//             SM.CXVSCROLL => 16,
//             SM.CYHSCROLL => 16,
//             SM.CYCAPTION => 19,
//             SM.CXBORDER => 1,
//             SM.CYBORDER => 1,
//             SM.CXFIXEDFRAME => 3,
//             SM.CYFIXEDFRAME => 3,
//             SM.CYVTHUMB => 16,
//             SM.CXHTHUMB => 16,
//             SM.CXICON => 32,
//             SM.CYICON => 32,
//             SM.CXCURSOR => 32,
//             SM.CYCURSOR => 32,
//             SM.CYMENU => 19,
//             SM.CYKANJIWINDOW => 0,
//             SM.MOUSEPRESENT => 1,
//             SM.CYVSCROLL => 16,
//             SM.CXHSCROLL => 16,
//             SM.DEBUG => 0,
//             SM.SWAPBUTTON => 0,
//             SM.CXMIN => 112,
//             SM.CYMIN => 27,
//             SM.CXSIZE => 18,
//             SM.CYSIZE => 18,
//             SM.CXFRAME => 4,
//             SM.CYFRAME => 4,
//             SM.CXMINTRACK => 112,
//             SM.CYMINTRACK => 27,
//             SM.CXDOUBLECLK => 4,
//             SM.CYDOUBLECLK => 4,
//             SM.CXICONSPACING => 91,
//             SM.CYICONSPACING => 91,
//             SM.MENUDROPALIGNMENT => 0,
//             SM.PENWINDOWS => 0,
//             SM.DBCSENABLED => 0,
//             SM.CMOUSEBUTTONS => 5,
//             SM.SECURE => 0,
//             SM.CXEDGE => 2,
//             SM.CYEDGE => 2,
//             SM.CXMINSPACING => 160,
//             SM.CYMINSPACING => 24,
//             SM.CXSMICON => 16,
//             SM.CYSMICON => 16,
//             SM.CYSMCAPTION => 16,
//             SM.CXSMSIZE => 12,
//             SM.CYSMSIZE => 15,
//             SM.CXMENUSIZE => 18,
//             SM.CYMENUSIZE => 18,
//             SM.ARRANGE => 8,
//             SM.NETWORK => 3,
//             SM.CLEANBOOT => 0,
//             SM.CXDRAG => 4,
//             SM.CYDRAG => 4,
//             SM.SHOWSOUNDS => 0,
//             SM.CXMENUCHECK => 13,
//             SM.CYMENUCHECK => 13,
//             SM.SLOWMACHINE => 0,
//             SM.MIDEASTENABLED => 0,
//             SM.MOUSEWHEELPRESENT => 1,
//             SM.XVIRTUALSCREEN => 0,
//             SM.YVIRTUALSCREEN => 0,
//             SM.CMONITORS => 1,
//             SM.SAMEDISPLAYFORMAT => 1,
//             SM.IMMENABLED => 0,
//             SM.CXFOCUSBORDER => 1,
//             SM.CYFOCUSBORDER => 1,
//             SM.TABLETPC => 0,
//             SM.MEDIACENTER => 0,
//             SM.REMOTESESSION => 0,
//             SM.REMOTECONTROL => 0,
//             _ => 0
//         };
//     }
//
//     internal enum Win32SystemColors
//     {
//         ActiveBorder = 0x0A,
//         ActiveCaption = 0x02,
//         ActiveCaptionText = 0x09,
//         AppWorkspace = 0x0C,
//         Control = 0x0F,
//         ControlDark = 0x10,
//         ControlDarkDark = 0x15,
//         ControlLight = 0x16,
//         ControlLightLight = 0x14,
//         ControlText = 0x12,
//         Desktop = 0x01,
//         GradientActiveCaption = 0x1B,
//         GradientInactiveCaption = 0x1C,
//         GrayText = 0x11,
//         Highlight = 0x0D,
//         HighlightText = 0x0E,
//         HotTrack = 0x1A,
//         InactiveBorder = 0x0B,
//         InactiveCaption = 0x03,
//         InactiveCaptionText = 0x13,
//         Info = 0x18,
//         InfoText = 0x17,
//         Menu = 0x04,
//         MenuBar = 0x1E,
//         MenuHighlight = 0x1D,
//         MenuText = 0x07,
//         ScrollBar = 0x00,
//         Window = 0x05,
//         WindowFrame = 0x06,
//         WindowText = 0x08
//     }
//
//     internal enum SM
//     {
//         CXSCREEN = 0,
//         CYSCREEN = 1,
//         CXVSCROLL = 2,
//         CYHSCROLL = 3,
//         CYCAPTION = 4,
//         CXBORDER = 5,
//         CYBORDER = 6,
//         CXFIXEDFRAME = 7,
//         CYFIXEDFRAME = 8,
//         CYVTHUMB = 9,
//         CXHTHUMB = 10,
//         CXICON = 11,
//         CYICON = 12,
//         CXCURSOR = 13,
//         CYCURSOR = 14,
//         CYMENU = 15,
//         CXFULLSCREEN = 16,
//         CYFULLSCREEN = 17,
//         CYKANJIWINDOW = 18,
//         MOUSEPRESENT = 19,
//         CYVSCROLL = 20,
//         CXHSCROLL = 21,
//         DEBUG = 22,
//         SWAPBUTTON = 23,
//         CXMIN = 28,
//         CYMIN = 29,
//         CXSIZE = 30,
//         CYSIZE = 31,
//         CXFRAME = 32,
//         CXSIZEFRAME = CXFRAME,
//         CYFRAME = 33,
//         CYSIZEFRAME = CYFRAME,
//         CXMINTRACK = 34,
//         CYMINTRACK = 35,
//         CXDOUBLECLK = 36,
//         CYDOUBLECLK = 37,
//         CXICONSPACING = 38,
//         CYICONSPACING = 39,
//         MENUDROPALIGNMENT = 40,
//         PENWINDOWS = 41,
//         DBCSENABLED = 42,
//         CMOUSEBUTTONS = 43,
//         SECURE = 44,
//         CXEDGE = 45,
//         CYEDGE = 46,
//         CXMINSPACING = 47,
//         CYMINSPACING = 48,
//         CXSMICON = 49,
//         CYSMICON = 50,
//         CYSMCAPTION = 51,
//         CXSMSIZE = 52,
//         CYSMSIZE = 53,
//         CXMENUSIZE = 54,
//         CYMENUSIZE = 55,
//         ARRANGE = 56,
//         CXMINIMIZED = 57,
//         CYMINIMIZED = 58,
//         CXMAXTRACK = 59,
//         CYMAXTRACK = 60,
//         CXMAXIMIZED = 61,
//         CYMAXIMIZED = 62,
//         NETWORK = 63,
//         CLEANBOOT = 67,
//         CXDRAG = 68,
//         CYDRAG = 69,
//         SHOWSOUNDS = 70,
//         CXMENUCHECK = 71,
//         CYMENUCHECK = 72,
//         SLOWMACHINE = 73,
//         MIDEASTENABLED = 74,
//         MOUSEWHEELPRESENT = 75,
//         XVIRTUALSCREEN = 76,
//         YVIRTUALSCREEN = 77,
//         CXVIRTUALSCREEN = 78,
//         CYVIRTUALSCREEN = 79,
//         CMONITORS = 80,
//         SAMEDISPLAYFORMAT = 81,
//         IMMENABLED = 82,
//         CXFOCUSBORDER = 83,
//         CYFOCUSBORDER = 84,
//         TABLETPC = 86,
//         MEDIACENTER = 87,
//         REMOTESESSION = 0x1000,
//         REMOTECONTROL = 0x2001,
//     }
// }