name: Build

on:
  push:
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.1
        with:
          dotnet-version: "9.0.x"
      - name: Build
        run: |
          dotnet workload restore
          dotnet build --configuration Release