name: Publish package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3.0.1
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run:  |
          dotnet workload restore
          dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish the package
        run: dotnet nuget push "src/*/bin/Release/*.nupkg" -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json